// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'book_source.dart';

BookSource _$BookSourceFromJson(Map<String, dynamic> json) => BookSource(
      bookSourceUrl: json['bookSourceUrl'] as String?,
      bookSourceName: json['bookSourceName'] as String?,
      bookSourceGroup: json['bookSourceGroup'] as String?,
      bookSourceType: json['bookSourceType'] as int?,
      bookSourceComment: json['bookSourceComment'] as String?,
      searchUrl: json['searchUrl'] as String?,
      exploreUrl: json['exploreUrl'] as String?,
      exploreScreen: json['exploreScreen'] as String?,
      ruleSearch: json['ruleSearch'],
      ruleExplore: json['ruleExplore'],
      ruleBookInfo: json['ruleBookInfo'],
      ruleToc: json['ruleToc'],
      ruleContent: json['ruleContent'],
      ruleReview: json['ruleReview'],
      enabled: json['enabled'] as bool?,
      enabledExplore: json['enabledExplore'] as bool?,
      customOrder: json['customOrder'] as int?,
      lastUpdateTime: json['lastUpdateTime'] as int?,
      respondTime: json['respondTime'] as int?,
      weight: json['weight'] as int?,
      variable: json['variable'] as String?,
      header: json['header'] as String?,
      loginUrl: json['loginUrl'] as String?,
      loginUi: json['loginUi'] as String?,
      loginCheckJs: json['loginCheckJs'] as String?,
      variableComment: json['variableComment'] as String?,
      checkKeyWord: json['checkKeyWord'] as String?,
      eventListener: json['eventListener'] as bool?,
      customButton: json['customButton'] as bool?,
    );

Map<String, dynamic> _$BookSourceToJson(BookSource instance) => <String, dynamic>{
      'bookSourceUrl': instance.bookSourceUrl,
      'bookSourceName': instance.bookSourceName,
      'bookSourceGroup': instance.bookSourceGroup,
      'bookSourceType': instance.bookSourceType,
      'bookSourceComment': instance.bookSourceComment,
      'searchUrl': instance.searchUrl,
      'exploreUrl': instance.exploreUrl,
      'exploreScreen': instance.exploreScreen,
      'ruleSearch': instance.ruleSearch,
      'ruleExplore': instance.ruleExplore,
      'ruleBookInfo': instance.ruleBookInfo,
      'ruleToc': instance.ruleToc,
      'ruleContent': instance.ruleContent,
      'ruleReview': instance.ruleReview,
      'enabled': instance.enabled,
      'enabledExplore': instance.enabledExplore,
      'customOrder': instance.customOrder,
      'lastUpdateTime': instance.lastUpdateTime,
      'respondTime': instance.respondTime,
      'weight': instance.weight,
      'variable': instance.variable,
      'header': instance.header,
      'loginUrl': instance.loginUrl,
      'loginUi': instance.loginUi,
      'loginCheckJs': instance.loginCheckJs,
      'variableComment': instance.variableComment,
      'checkKeyWord': instance.checkKeyWord,
      'eventListener': instance.eventListener,
      'customButton': instance.customButton,
    };
